terminate called after throwing an instance of 'std::runtime_error'
  what():  You cannot pull var 'g' from population 'projection_402_exc2to00_0'